import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import TopHeader from '@/components/layouts/TopHeader'
import Sidebar from '@/components/layouts/SideHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark flex flex-col h-screen`}>
        <TopHeader/>
        <div className='flex md:flex-row flex-col w-full'>
        <Sidebar/>
        {children}
        </div>
        </body>
    </html>
  )
}
